spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz90se4amyr15cx5m3o.mysql.rds.aliyuncs.com:3306/beauty
    username: beauty123_a
    password: Beauty123
  data:
    redis:
      host: r-wz93vhmwcf2sgvsenh.redis.rds.aliyuncs.com
      port: 6379
server:
  port: 8080

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.springframework.security: debug

aliyun:
  oss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5t7i5X9gkf1Fp8fApk5r
    accessKeySecret: YwQtsNKSbVLnqBn2LbhSVxoez53gTK
    bucketName: ai-beauty

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto #默认id为自增
#
logger:
  com.baomidou.mybatisplus: DEBUG


